'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';

const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
const clamp = (value, min, max) => Math.min(Math.max(Number.isFinite(Number(value)) ? Number(value) : min, min), max);

function Input({ label, value, setValue, prefix, suffix, hint, min = 0.01, max = 100000000, step = 1, allowPartial = false }) {
  const updateValue = (event) => {
    const raw = event.target.value;
    setValue(allowPartial ? raw : clamp(raw, min, max));
  };
  return <label className="block"><span className="mb-2 block font-mono text-xs uppercase tracking-wider text-white/55">{label}</span><div className="flex items-center rounded-xl border border-white/10 bg-black/20 px-3 focus-within:border-cyan-300/50">{prefix && <span className="mr-1 text-white/45">{prefix}</span>}<input aria-label={label} type="number" min={min} max={max} step={step} value={value} onChange={updateValue} onBlur={() => { if (allowPartial) setValue(clamp(value, min, max)); }} className="w-full bg-transparent py-3 text-base font-semibold text-white outline-none" />{suffix && <span className="ml-2 text-white/45">{suffix}</span>}</div>{hint && <span className="mt-1.5 block text-xs text-white/45">{hint}</span>}</label>;
}

function Tile({ label, value, tone = 'text-white' }) { return <div className="rounded-xl border border-white/10 bg-black/20 p-4"><p className="font-mono text-[10px] uppercase tracking-wider text-white/45">{label}</p><p className={`mt-1 text-xl font-bold ${tone}`}>{value}</p></div>; }

export default function AccountSurvivalCalculatorNext() {
  const [accountSize, setAccountSize] = useState(50000);
  const [drawdown, setDrawdown] = useState(2000);
  const [mode, setMode] = useState('dollar');
  const [dailyDollar, setDailyDollar] = useState(200);
  const [dailyPercent, setDailyPercent] = useState(1);
  const [target, setTarget] = useState(22);
  const [snapshot, setSnapshot] = useState({ accountSize: 50000, drawdown: 2000, mode: 'dollar', dailyDollar: 200, dailyPercent: 1 });

  const liveDailyLoss = mode === 'percentage' ? accountSize * dailyPercent / 100 : dailyDollar;
  const result = useMemo(() => {
    const daily = snapshot.mode === 'percentage' ? snapshot.accountSize * snapshot.dailyPercent / 100 : snapshot.dailyDollar;
    const sessions = Math.floor(snapshot.drawdown / daily);
    const capacity = daily / snapshot.drawdown * 100;
    const tone = sessions < 10 ? { label: 'Small survival buffer', color: 'red', icon: '🚨' } : sessions <= 20 ? { label: 'Moderate survival buffer', color: 'amber', icon: '⚠' } : { label: 'Strong survival buffer', color: 'green', icon: '🛡' };
    return { daily, sessions, capacity, tone };
  }, [snapshot]);
  const suggestedDaily = drawdown / target;
  const reductionOptions = [100, 200, 300, 400, 500].filter((value) => value <= snapshot.drawdown).sort((a, b) => b - a);
  const color = result.tone.color === 'red' ? 'text-red-400' : result.tone.color === 'amber' ? 'text-amber-300' : 'text-emerald-400';
  const border = result.tone.color === 'red' ? 'border-red-400/25 bg-red-400/[0.05]' : result.tone.color === 'amber' ? 'border-amber-300/25 bg-amber-300/[0.05]' : 'border-emerald-400/25 bg-emerald-400/[0.05]';

  return <div className="mx-auto max-w-4xl pb-12">
    <section className="mb-8 text-center"><div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl border border-cyan-300/20 bg-cyan-300/5 text-3xl">🛡</div><p className="font-mono text-xs uppercase tracking-[0.2em] text-cyan-300">Free risk calculator</p><h1 className="mt-3 font-display text-3xl font-bold text-white md:text-4xl">Account Survival Calculator</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-relaxed text-white/55">See how many losing trading sessions your drawdown can absorb from your planned daily loss.</p></section>

    <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-5 md:p-6"><div className="mb-6"><p className="font-mono text-xs uppercase tracking-wider text-cyan-300">Your risk boundary</p><h2 className="mt-1 text-xl font-semibold text-white">Account and daily loss plan</h2></div><div className="grid gap-4 md:grid-cols-2"><Input label="Account size" value={accountSize} setValue={setAccountSize} prefix="$" /><Input label="Maximum drawdown" value={drawdown} setValue={setDrawdown} prefix="$" hint="Personal account: use your account balance. Prop account: use the firm’s maximum drawdown." /></div>
      <div className="mt-5 rounded-xl border border-white/10 bg-black/20 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-xs uppercase tracking-wider text-white/55">Planned daily loss</p><p className="mt-1 text-sm text-white/45">Set your daily risk boundary in dollars or as a percentage of account size.</p></div><div className="flex rounded-lg border border-white/10 p-1" role="radiogroup" aria-label="Daily loss format"><button type="button" role="radio" aria-checked={mode === 'dollar'} onClick={() => setMode('dollar')} className={`rounded-md px-4 py-2 text-sm font-semibold ${mode === 'dollar' ? 'bg-cyan-300/10 text-cyan-200' : 'text-white/45'}`}>$</button><button type="button" role="radio" aria-checked={mode === 'percentage'} onClick={() => setMode('percentage')} className={`rounded-md px-4 py-2 text-sm font-semibold ${mode === 'percentage' ? 'bg-cyan-300/10 text-cyan-200' : 'text-white/45'}`}>%</button></div></div>
      <div className="mt-4 grid gap-4 sm:grid-cols-2">{mode === 'dollar' ? <Input label="Planned daily loss" value={dailyDollar} setValue={setDailyDollar} prefix="$" max={drawdown} /> : <Input label="Planned daily loss" value={dailyPercent} setValue={setDailyPercent} suffix="%" max={100} step={0.01} allowPartial hint={`Converted from account size: ${money.format(liveDailyLoss)} per session.`} />}<Tile label="Daily loss in dollars" value={money.format(liveDailyLoss)} tone="text-cyan-200" /></div></div>
      <button type="button" onClick={() => setSnapshot({ accountSize, drawdown, mode, dailyDollar, dailyPercent })} className="mt-6 w-full rounded-xl px-5 py-3.5 text-sm font-semibold text-[#08080f]" style={{ background: 'linear-gradient(120deg, #a78bfa, #22d3ee)' }}>Calculate account survival →</button></section>

    <section className={`mt-5 rounded-2xl border p-6 text-center md:p-8 ${border}`}><p className="font-mono text-xs uppercase tracking-[0.2em] text-white/55">{result.tone.icon} Your account can survive</p><p className={`mt-3 text-8xl font-bold tracking-tight md:text-9xl ${color}`}>{result.sessions}</p><h2 className="mt-2 text-xl font-semibold text-white md:text-2xl">Consecutive losing trading sessions</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-relaxed text-white/60">If every trading day ends at your planned maximum loss of <span className="font-semibold text-white">{money.format(result.daily)}</span>, your account reaches its drawdown limit after <span className="font-semibold text-white">{result.sessions} consecutive losing sessions</span>.</p><div className="mx-auto mt-6 max-w-md"><p className="font-mono text-xs uppercase tracking-wider text-white/45">Daily loss capacity</p><div className="mt-2 h-3 overflow-hidden rounded-full bg-white/10"><div className={`h-full rounded-full ${result.tone.color === 'red' ? 'bg-red-400' : result.tone.color === 'amber' ? 'bg-amber-300' : 'bg-emerald-400'}`} style={{ width: `${Math.min(result.capacity, 100)}%` }} /></div><p className="mt-2 text-sm text-white/60">Each losing day consumes <span className={`font-bold ${color}`}>{result.capacity.toFixed(1)}%</span> of your total drawdown.</p></div></section>

    <section className="mt-5 rounded-2xl border border-white/10 bg-white/[0.03] p-5 md:p-6"><p className="font-mono text-xs uppercase tracking-wider text-cyan-300">Why this is the answer</p><div className="mt-5 grid items-center gap-3 text-center sm:grid-cols-[1fr_auto_1fr_auto_1fr]"><Tile label="Maximum drawdown" value={money.format(snapshot.drawdown)} tone="text-cyan-200" /><span className="text-3xl text-white/45">÷</span><Tile label="Planned daily loss" value={money.format(result.daily)} tone="text-cyan-200" /><span className="text-3xl text-white/45">=</span><Tile label="Survival sessions" value={result.sessions} tone={color} /></div>{snapshot.mode === 'percentage' && <p className="mt-5 rounded-xl border border-white/10 bg-black/20 p-4 text-sm leading-relaxed text-white/55">Your {snapshot.dailyPercent}% daily loss is calculated from the <span className="text-white">{money.format(snapshot.accountSize)} account size</span>, then compared with the <span className="text-white">{money.format(snapshot.drawdown)} maximum drawdown</span>.</p>}<div className="mt-5 rounded-xl border border-white/10 bg-black/20 p-4"><p className="font-semibold text-white">What does this mean?</p><p className="mt-1 text-sm leading-relaxed text-white/60">Your planned daily loss is a boundary, not a forecast. This calculation simply shows the number of full loss sessions your stated drawdown can absorb.</p></div></section>

    <section className="mt-5 rounded-2xl border border-white/10 bg-white/[0.03] p-5 md:p-6"><p className="font-mono text-xs uppercase tracking-wider text-cyan-300">Plan your buffer</p><h2 className="mt-1 text-xl font-semibold text-white">How much can I lose per day?</h2><p className="mt-2 text-sm text-white/55">Choose a survival target. One month equals 22 trading sessions.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{[[30, '30 calendar days'], [22, '22 trading sessions'], [22, '1 month']].map(([days, label], index) => <button key={`${label}-${index}`} type="button" onClick={() => setTarget(days)} className={`rounded-xl border p-4 text-left ${target === days && (index === 1 || index === 2) ? 'border-cyan-300/50 bg-cyan-300/[0.07]' : 'border-white/10 bg-black/20'}`}><p className="font-semibold text-white">{label}</p><p className="mt-1 text-xs text-white/45">Daily limit: {money.format(drawdown / days)}</p></button>)}</div><div className="mt-4 rounded-xl border border-cyan-300/20 bg-cyan-300/[0.05] p-4"><p className="font-mono text-[10px] uppercase tracking-wider text-cyan-200">For {target} sessions</p><p className="mt-1 text-2xl font-bold text-white">Keep planned daily loss at or below {money.format(suggestedDaily)}</p></div></section>

    <section className="mt-5 rounded-2xl border border-white/10 bg-white/[0.03] p-5 md:p-6"><p className="font-mono text-xs uppercase tracking-wider text-cyan-300">What if I reduce my daily loss?</p><p className="mt-2 text-sm text-white/55">Small changes to daily loss can extend the number of consecutive loss sessions your drawdown can absorb.</p><div className="mt-5 grid gap-3 sm:grid-cols-5">{reductionOptions.map((value) => { const sessions = Math.floor(snapshot.drawdown / value); const extra = sessions - result.sessions; return <button type="button" key={value} onClick={() => { setMode('dollar'); setDailyDollar(value); setSnapshot({ accountSize, drawdown, mode: 'dollar', dailyDollar: value, dailyPercent }); }} className="rounded-xl border border-white/10 bg-black/20 p-3 text-left hover:border-cyan-300/35"><p className="font-mono text-[10px] text-white/45">DAILY LOSS</p><p className="mt-1 font-bold text-white">{money.format(value)}</p><p className="mt-2 text-sm text-cyan-200">{sessions} sessions</p>{extra > 0 && <p className="mt-1 text-xs text-emerald-400">+{extra} more</p>}</button>; })}</div></section>

    <section className="mt-5 rounded-2xl border border-cyan-300/20 bg-cyan-300/[0.05] p-5 text-center"><h2 className="font-semibold text-white">Want live tracking?</h2><p className="mx-auto mt-2 max-w-md text-sm leading-relaxed text-white/55">Log trades in PropLogAI to keep your risk and review evidence in one place.</p><Link href="/login" className="mt-5 inline-block rounded-xl px-6 py-3 text-sm font-semibold text-[#08080f]" style={{ background: 'linear-gradient(120deg, #a78bfa, #22d3ee)' }}>Start Free →</Link></section>
  </div>;
}
