"use client";
import { useState } from 'react';

const guardrails = [
  { name: 'Risk per trade', value: '1.0', unit: '%', version: 'v3', required: true },
  { name: 'Daily loss limit', value: '500', unit: '$', version: 'v2', required: true },
  { name: 'Stop-on-profit', value: '1,000', unit: '$', version: 'v1', required: false },
];
const focus = [
  ['◉','Only enter a planned A-grade setup.','4','v2'], ['ϟ','Stop trading after 2 consecutive losses.','3','v1'], ['▥','Wait for candle-close confirmation.','5','v2'], ['⊘','Do not enter an already extended setup.','2','v1'],
];
const library = [
  ['Max 2 open trades at once','Risk','v1'], ['Avoid trading news events','Setup','v2'], ['Do not revenge trade','Behavior','v1'], ['Break after 3 losing trades','Behavior','v1'],
];

export default function RulesMockupWorkspace() {
  const [selected, setSelected] = useState(0);
  const [tab, setTab] = useState('Rules');
  const [filter, setFilter] = useState('All');
  return <div className="px-4 py-6 sm:px-6"><div className="mx-auto max-w-6xl">
    <div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h1 className="font-display text-3xl font-bold sm:text-4xl">Non-negotiable rules</h1><p className="mt-1 text-sm text-white/60">Build an unlimited Rulebook. Keep only 3–5 Focus rules active for fast reviews.</p></div><button className="rounded-xl px-5 py-3 text-sm font-semibold text-[#08080f]" style={{background:'linear-gradient(120deg,#a78bfa,#22d3ee)'}}>＋ Add rule</button></div>
    <div className="mb-3 flex rounded-xl border border-white/10 bg-white/[0.025] p-1">{['Today','Rules','Review','Progress'].map(x=><button key={x} onClick={()=>setTab(x)} className={'flex-1 rounded-lg px-3 py-3 text-sm '+(tab===x?'bg-white/[0.09] font-semibold text-white':'text-white/55')}>{x}</button>)}</div>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_325px]"><main className="space-y-4"><section className="rounded-2xl border border-white/10 bg-white/[0.025] p-4"><div className="mb-3 flex items-center justify-between"><div><div className="font-mono text-xs uppercase tracking-[.18em] text-violet-300">Required guardrails ⓘ</div><div className="mt-1 text-xs text-white/45">Required rules cannot be deleted during an active programme.</div></div></div>{guardrails.map((g,i)=><button key={g.name} onClick={()=>setSelected(i)} className={'grid w-full grid-cols-[18px_1fr_100px_72px_auto] items-center gap-3 border-t border-white/[.08] py-3 text-left first:border-t-0 '+(selected===i?'rounded-xl bg-violet-400/[.07] px-2 ring-1 ring-violet-400/60':'')}><span className="text-white/40">⠿</span><span className="font-medium">◉　{g.name}</span><input defaultValue={g.value} onClick={e=>e.stopPropagation()} className="w-full rounded-lg border border-white/15 bg-black/25 px-3 py-2 text-sm"/><span className="rounded-md border border-violet-400/70 px-2 py-2 text-center font-mono text-xs">{g.unit}</span><span className={'font-mono text-xs '+(g.required?'text-emerald-300':'text-amber-300')}>{g.required?'Required':'Optional'} · {g.version}　✎ Edit</span></button>)}</section>
    <section className="rounded-2xl border border-white/10 bg-white/[0.025] p-4"><div className="mb-3 flex items-center justify-between"><div><div className="font-mono text-xs uppercase tracking-[.18em] text-violet-300">Focus rules · 4 of 5 active ⓘ</div><div className="mt-1 text-xs text-white/55">This small set keeps review sessions fast and decision-focused.</div></div><button className="rounded-lg border border-violet-400/60 px-3 py-2 text-xs text-violet-200">＋ Add from Rulebook</button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{focus.map(([icon,name,evidence,version])=><div key={name} className="rounded-xl border border-white/10 bg-black/20 p-4"><div className="flex justify-between"><span className="text-2xl text-violet-300">{icon}</span><span className="text-white/50">×</span></div><div className="mt-3 text-sm font-medium leading-relaxed">{name}</div><div className="mt-4 font-mono text-xs text-white/45">▣ {evidence} evidence　{version}</div></div>)}</div><div className="mt-4 flex justify-between text-xs text-white/50"><span>4 of 5 active. Remove one to add another.</span><span className="text-violet-300 underline">Manage Focus rules</span></div></section>
    <section className="rounded-2xl border border-white/10 bg-white/[0.025] p-4"><div className="font-mono text-xs uppercase tracking-[.18em] text-violet-300">Rulebook library · 12 rules</div><div className="mt-2 text-xs text-white/55">Optional rules may be edited, archived, or deleted; version history remains.</div><div className="mt-3 flex gap-1 rounded-xl border border-white/10 p-1 w-fit">{['All','Risk','Setup','Behavior'].map(x=><button key={x} onClick={()=>setFilter(x)} className={'rounded-lg px-4 py-2 text-xs '+(filter===x?'bg-violet-500/20 text-violet-200':'text-white/50')}>{x}</button>)}</div><div className="mt-3 overflow-hidden rounded-xl border border-white/10">{library.filter(r=>filter==='All'||r[1]===filter).map(([name,type,v])=><div key={name} className="grid grid-cols-[25px_1fr_100px_70px_auto] items-center gap-3 border-t border-white/[.08] px-3 py-3 first:border-t-0"><span className="text-white/40">⠿</span><span className="text-sm">◉　{name}</span><span className="text-xs text-white/55">{type}</span><span className="font-mono text-xs text-white/45">{v}</span><span className="text-xs text-white/55">✎ Edit　▣ Archive　<span className="text-red-400">⌫</span></span></div>)}</div><div className="mt-3 text-center text-xs text-white/45">Showing 1–12 of 12 rules</div></section></main>
    <aside className="rounded-2xl border border-white/15 bg-[linear-gradient(180deg,rgba(18,18,26,.95),rgba(7,7,11,.95))] p-5"><div className="flex justify-between"><div className="grid h-11 w-11 place-items-center rounded-full border border-violet-300/50 text-xl text-violet-300">◉</div><span>×</span></div><h2 className="mt-4 font-display text-xl font-semibold">{guardrails[selected].name}</h2><div className="mt-7 font-mono text-xs uppercase tracking-[.18em] text-violet-300">Current value</div><div className="mt-2 text-3xl font-bold">{guardrails[selected].value}{guardrails[selected].unit}</div><div className="mt-6 border-t border-white/10 pt-5"><div className="font-mono text-xs uppercase tracking-[.18em] text-violet-300">Version history</div>{['v3　1%','v2　0.5%','v1　$100'].map((v,i)=><div key={v} className="mt-4 border-l border-white/20 pl-4"><div className="font-semibold">{v} {i===0&&<span className="float-right text-xs text-emerald-300">Current</span>}</div><div className="mt-1 text-xs text-white/45">Effective Jul {30-i*8}, 2025 (Day {6-i*6})</div></div>)}</div><div className="mt-6 rounded-xl border border-white/10 bg-black/20 p-4 text-sm leading-relaxed text-white/65">Completed reviews keep their original rule version for accuracy and consistency.</div><div className="mt-6 border-t border-white/10 pt-5"><div className="font-mono text-xs uppercase tracking-[.18em] text-violet-300">About this rule</div><p className="mt-3 text-sm leading-relaxed text-white/65">Limit the maximum risk per trade to protect account capital and ensure long-term survival.</p></div></aside></div>
  </div></div>
}
